version: '1'
services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000" 
    depends_on:
      - redis
      - celery
    networks:
      - network

  celery:
    build:
      context: .
    depends_on:
      - rabbitmq
      - redis
    networks:
      - network
    command: celery -A task worker --loglevel=INFO --concurrency=1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
                   
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
    networks:
      - network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
